on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

name: Run tests with coverage tracing
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      if: success()
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run tests
      run: go test -v -covermode=count -coverprofile=coverage.out
    - name: Convert coverage to lcov
      uses: jandelgado/gcov2lcov-action@v1
    - name: Publish to Coveralls
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: coverage.lcov
